Feature/offer detailed info
pw-software-engineering/j-team pull request #126
Opened 2021-05-31 18:45 UTC by j-janiszewski

Get offerinfo query added + tests

2021-05-31 20:37 UTC, cbanach requested changes

2021-05-31 20:37 UTC, cbanach commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +            var offer = _context.Offers.Where(x => x.HotelId == request.hotelId && x.OfferId == request.offerId).FirstOrDefault();
brakuje Include (x=> x.Rooms) przy pobieraniu oferty

2021-05-31 20:37 UTC, cbanach commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +                room.Reservations=room.Reservations.OrderBy(x => x.FromTime).ToList();
trzeba zrobić też include na reservations (tak jak jest teraz zawsze będzie null)

2021-05-31 20:37 UTC, cbanach commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +                room.Reservations=room.Reservations.OrderBy(x => x.FromTime).ToList();
nie przypisywał bym też nic do navigation properties, stwórz lepiej zmienną pomocniczną (linia 46)

2021-06-05 08:01 UTC, j-janiszewski commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +            var offer = _context.Offers.Where(x => x.HotelId == request.hotelId && x.OfferId == request.offerId).FirstOrDefault();
dodałem

2021-06-05 08:01 UTC, j-janiszewski commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +                room.Reservations=room.Reservations.OrderBy(x => x.FromTime).ToList();
dodałem

2021-06-05 08:01 UTC, j-janiszewski commented on src/Application/Hotels/Queries/GetOfferInfo/GetOfferInfoQuery.cs
> +                room.Reservations=room.Reservations.OrderBy(x => x.FromTime).ToList();
zmieniłem

2021-06-05 10:38 UTC, merged