Feature/d bmodels
pw-software-engineering/j-team pull request #33
Opened 2021-03-27 22:31 UTC by oskar1410

Added Hotel, Offer and Room with REST API

2021-03-28 11:12 UTC, cbanach requested changes

2021-03-28 11:12 UTC, cbanach commented on src/Infrastructure/Persistence/Configurations/HotelConfiguration.cs
> -            builder.Property(t => t.Title)
w HotelConfiguration powinny być opisane wszystkie pola + klucze, tzn:
IsRequired(true/false),
MaxLength (to opcjonalnie),
HasOne/HasMany dla relacji

2021-03-28 11:12 UTC, cbanach commented on src/Domain/Entities/Offer.cs
> +        public List<Room> Rooms { get; set;}
Rooms powinno być virtual

2021-03-28 11:12 UTC, cbanach commented on src/Domain/Entities/Hotel.cs
> +        public List<Offer> Offers { get; set; }
Offers powinno być virtual

2021-03-28 11:12 UTC, cbanach commented on src/Infrastructure/Persistence/Configurations/OfferConfiguration.cs
> +{
to samo co w hotel

2021-03-28 11:12 UTC, cbanach commented on src/Infrastructure/Persistence/Configurations/RoomConfiguration.cs
> +    public class RoomConfiguration : IEntityTypeConfiguration<Room>
to samo co w hotel

2021-03-28 11:12 UTC, cbanach commented on src/Domain/Entities/Room.cs
> +        public Offer Offer { get; set; }
virtual

2021-03-28 11:12 UTC, cbanach commented on src/Application/Rooms/Commands/CreateRoom/CreateRoomCmd.cs
> +    public class CreateOfferCmdHandler : IRequestHandler<CreateRoomCmd, int>
tu rename trzeba zrobic na CreateRoom

2021-03-28 11:12 UTC, cbanach commented on src/Application/Offers/Queries/GetOffersWithPagination/GetOffersWithPaginationQuery.cs
> +    public class GetHotelsWithPaginationQueryHandler : IRequestHandler<GetOffersWithPaginationQuery, PaginatedList<OfferDto>>
GetOffers zamiast GetHotels

2021-03-28 11:12 UTC, cbanach commented on src/Application/Offers/Commands/UpdateOffer/UpdateOfferCmd.cs
> +            entity.Title = request.Title == null ? entity.Title : request.Title;
krótszy zapis to entity.Title = request.Title ?? entity.Title

2021-03-28 11:12 UTC, cbanach commented on src/Application/Offers/Commands/UpdateOffer/UpdateOfferCmd.cs
> +                entity.IsActive = (bool)request.IsActive;
zamiast casta na bool lepiej zrobic request.IsActive.Value

2021-03-29 17:13 UTC, teodorstupnicki commented
część zmian zaimplementowana, reszta zawarta w issue #34

2021-03-29 17:13 UTC, merged