Feature/d bmodels
pw-software-engineering/j-team pull request #41
Opened 2021-04-01 13:58 UTC by oskar1410

Konwerter do obrazków (żeby dodać do bazy): https://base64.guru/converter/encode/file

2021-04-06 09:36 UTC, CezaryBanach requested changes

2021-04-06 09:36 UTC, CezaryBanach commented on src/Application/Common/Mappings/MappingProfile.cs
> +            //    .ForMember(dest => dest.OfferId, opt => opt.MapFrom(src => src.Offers));
jak niepotrzebne to lepiej wywalić komentarze

2021-04-06 09:36 UTC, CezaryBanach commented on src/Domain/Entities/Review.cs
> +        public string content { get; set; }
Content zamiast content, to samo rating

2021-04-06 09:36 UTC, CezaryBanach commented on src/Domain/Entities/OfferFile.cs
> +namespace HotelReservationSystem.Domain.Entities
czemu 3 takie same modele na pliki? na jednym modelu można przecież wiele relacji zdefiniować

2021-04-06 09:36 UTC, CezaryBanach commented on src/Domain/Entities/Client.cs
> +        public List<Reservation> Reservations { get; set; }
virtual

2021-04-06 09:36 UTC, CezaryBanach commented on src/Domain/Entities/OfferFile.cs
> +namespace HotelReservationSystem.Domain.Entities
jeśli z jakiegoś powodu musi tak być to zrobiłbym klasę/interfejs bazowy

2021-04-06 09:36 UTC, CezaryBanach commented on src/Domain/Entities/Hotel.cs
> +        public List<HotelFile> Pictures { get; set; }
virtual

2021-04-06 09:36 UTC, CezaryBanach commented on src/Application/Rooms/RoomDto.cs
> +        // public List<int> OfferId { get; set; }
tu ma zostać komentarz?

2021-04-06 09:36 UTC, CezaryBanach commented on src/Application/Rooms/Commands/CreateRoom/CreateRoomCmd.cs
> +        public int OfferID { get; set; }
czemu Id na ID?

2021-04-06 09:36 UTC, CezaryBanach commented on src/Application/Offers/OfferDto.cs
> +        // public byte[] OfferPreviewPicture { get; set; }
jeśli niepotrzebne to do wywalenia komentarze

2021-04-09 20:08 UTC, oskar1410 commented on src/Domain/Entities/OfferFile.cs
> +namespace HotelReservationSystem.Domain.Entities
jak chciałem dać relację 1 do 1 hotel-file, odpowiednio między własnościami HotelPreviewPicture i Hotel oraz jednocześnie relację 1 do wielu hotel-file, między Pictures i Hotel, to dostawałem błąd, że nie może być dwóch relacji między parą encji, więc zdecydowałem się na dwie encje plików (File oraz PreviewFile). Natomiast potem rozmnożyło się do czterech, ponieważ w File miałem dwa klucze obce, które były nullable (jeden do hotelu i jeden do oferty, a plik, należy raczej tylko do jednej z tych encji), w związku z czym pojawił się problem z kaskadowym usuwaniem. Na pewno da się to rozwiązać zgrabniej, ale szczerze to nie umiem

2021-04-09 20:41 UTC, oskar1410 commented on src/Application/Rooms/RoomDto.cs
> +        // public List<int> OfferId { get; set; }
finalnie ma być coś takiego jak OfferID w api -
![lista_wszystkich_pokoi](https://user-images.githubusercontent.com/74511056/114237888-01cee080-9984-11eb-9be5-800b591f6898.png), ale nie potrafiłem ogarnąć mappera, tak, żeby z własności Offers encji Room wyciągał OfferId dla każdego Offer (to nie powinno być problematyczne, ale wyskakują wyjątki, których nie rozumiałem)

2021-04-09 20:42 UTC, oskar1410 commented on src/Application/Common/Mappings/MappingProfile.cs
> +            //    .ForMember(dest => dest.OfferId, opt => opt.MapFrom(src => src.Offers));
To jest moja próba napisania mappera, o którym napisałem tu https://github.com/pw-software-engineering/j-team/pull/41#discussion_r607694884

2021-04-09 20:54 UTC, oskar1410 commented on src/Application/Rooms/Commands/CreateRoom/CreateRoomCmd.cs
> +        public int OfferID { get; set; }
w specyfikacji w endpointach używają ID

2021-04-09 20:57 UTC, oskar1410 commented on src/Application/Offers/OfferDto.cs
> +        // public byte[] OfferPreviewPicture { get; set; }
Tutaj też nie potrafiłem napisać mappera (PreviewOfferFile -> byte[]), a w dto powinno takie coś być

2021-04-10 15:47 UTC, merged