offer rooms add and remove
pw-software-engineering/j-team pull request #75
Opened 2021-04-26 18:21 UTC by teodorstupnicki

2021-04-26 19:06 UTC, cbanach requested changes

2021-04-26 19:06 UTC, cbanach commented on src/Application/Offers/Commands/DeleteOfferRoom/DeleteOfferRoomCmd.cs
> +    public class DeleteOfferRoomCmd : IRequest
Czy ten pokój można tak po prostu usunąć z oferty? nie ma jakichś edge casów jak jest w rezerwacji itd?

2021-04-26 19:06 UTC, cbanach commented on src/Application/Offers/Commands/AddOfferRoom/AddOfferRoomCmd.cs
> +using HotelReservationSystem.Application.Common.Interfaces;
przydałyby się testy do tego (może być w oddzielnym pr)

2021-04-26 19:10 UTC, teodorstupnicki commented on src/Application/Offers/Commands/DeleteOfferRoom/DeleteOfferRoomCmd.cs
> +    public class DeleteOfferRoomCmd : IRequest
według specyfikacji nie ma to wpływu na możliwość usunięcia pokoju z oferty

2021-04-27 10:33 UTC, teodorstupnicki commented on src/Application/Offers/Commands/AddOfferRoom/AddOfferRoomCmd.cs
> +using HotelReservationSystem.Application.Common.Interfaces;
dodałem do tego oddzielnego taska

2021-04-27 13:54 UTC, cbanach approved these changes

2021-04-27 15:36 UTC, merged